name: TestRunnerSnitch

on:
  workflow_call:
    inputs:
      test-names:
        required: true
        type: string
      num-cores:
        required: true
        type: number
      simulator:
        required: false
        default: "banshee"
        type: string      

jobs:
  test-runner-snitch:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pulp-platform/deeploy:main
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Deeploy
        run: pip install -e .
      - name: Run Test
        run: |
          testNames="${{ inputs.test-names }}"
          cd DeeployTest
          echo "$testNames" | while IFS= read -r testName; do
            if [[ -n "$testName" ]]; then
              echo "Running test: $testName"
              python testRunner_snitch.py -t Tests/$testName --simulator=banshee --cores=9 --toolchain_install_dir /app/install/riscv-llvm/
            fi
          done
        shell: bash